version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.2.0
    command: >
      -listen-client-urls http://0.0.0.0:2379
      -advertise-client-urls http://etcd:2379
  frontend:
    image: caltha/akka-cluster-etcd/monitor:latest
    environment:
      - CLUSTER_ROLE=frontend
    ports:
      - "8080:8080"
  backend:
    image: caltha/akka-cluster-etcd/monitor:latest
    environment:
      - CLUSTER_ROLE=backend
